export const routerConstants = {
	REGISTRATION: 'registration',
	ALLOW_LOCATION: 'allow-location',
	AUTOCOMPLETE_MAP: 'autocomplete-map',

	LOGIN: 'login',
	MAIN: 'main',
	HOME: 'home',
	STORE: 'store',
	ADDRESS: 'address',
	FAVORITE: 'favorite',
	ORDER_STATUSES: 'order-statuses',
	ORDERS: 'orders',
	SHOPS: 'shops',
	PROFILE_USER: 'profile-user',
	HISTORY: 'history',
	CART: 'cart',
	USER_UPDATE: 'user-update',
	FORGOT_PASSWORD: 'forgot-password',
	RESET_PASSWORD: 'reset-password',
	NEW_PASSWORD: 'new-password',

	TERM_SERVICE: 'terms-service',
	LEGAL_INFORMATION: 'legal-information',
	PRIVACY_POLICE: 'Privacy-police',

	//courier
	COURIER_REGISTER: 'courier-register',
	MAIN_COURIER: 'MAIN-COURIER',
	COURIER_ORDERS: 'courier-orders',
	COURIER_PICK_ORDER: 'courier-pick-order',
	COURIER_IN_PROGRESS: 'courier-in-progress',
	COURIER_TAKEN_ORDERS: 'courier-taken-orders',
	COURIER_COMPLETED_ORDERS: 'courier-completed-orders',
	COURIER_PROFILE: 'courier-profile',
}
