export const routerConstants = {
    REGISTRATION: 'registration',
    ALLOW_LOCATION: 'allow-location',
    AUTOCOMPLETE_MAP: 'autocomplete-map',
    RESET_PASSWORD: 'reset-password',
    LOGIN: 'login',
    MAIN: 'main',
    HOME: 'home',
    STORE: 'store',
    FAVORITE: 'favorite',
    ORDER_STATUSES: 'order-statuses ',
    SHOPS: 'shops',
    PROFILE_USER: 'profile-user',
    HISTORY: 'history',
    CART: 'cart',
}
